### ISSUE TITLE
How to modify the ft height of an HTML file

### ISSUE THREAD

**Issue by steedouble** [BeneSim/BeneOverlay#29]
The fixed conversion height is above 4900ft to FL. How to modify the HTML file to convert the height from above 11000ft to FL height?

**Comment by BeneSim** [comment]
Hi, you don't need to modify the HTML file you can simply change the transition altitude in the overlay under `Flight` -> `Transition Altitude`

![beneoverlay-ta](https://user-images.githubusercontent.com/29384538/73152785-77c58f80-40d1-11ea-8728-158ab27ce75f.png)

Does this solve your issue?

**Comment by steedouble** [comment]
Thank you very much

四川成都广中贸易有限公司

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Benjamin Isbarn"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月27日(星期一) 中午1:51
收件人:&nbsp;"BeneSim/BeneOverlay"<BeneOverlay@noreply.github.com&gt;;
抄送:&nbsp;"stee"<51379988@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BeneSim/BeneOverlay] How to modify the ft height of an HTML file (#29)



Hi, you don't need to modify the HTML file you can simply change the transition altitude in the overlay under Flight -&gt; Transition Altitude
 
 Does this solve your issue?
