### ISSUE TITLE
Progress Bar don´t show correct after OBS update

### ISSUE THREAD

**Issue by KBNOtaku** [BeneSim/BeneOverlay#35]
Hello

After updating my OBS BENE Overlay won´t show the Progress Bar correct anymore?

Screenshots:
![grafik](https://user-images.githubusercontent.com/56799893/155109282-0966c4a1-4f0e-443d-b0e9-d0175ea57b7a.png)
![grafik](https://user-images.githubusercontent.com/56799893/155109445-6dbd60d5-4659-465b-930a-e5f349e44be4.png)

I don't know have the OBS update can effect BENE Overlay?
I would be very thankfully if you can find a solution to that?

**Comment by BeneSim** [comment]
Fixed
